openapi: 3.0.0
info:
  title: API de Estudiantes
  version: 1.0.0
paths:
  /movieapp/v1/movies/search:
    get:
      tags:
        - Movies
      summary: Buscar peliculas
      parameters:
        - name: title
          in: query
          description: Título de la película
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoviesResponse'
  /movieapp/v1/movies/{imdbID}:
    get:
      tags:
        - Movies
      summary: Obtener detalles de una película
      parameters:
        - name: imdbID
          in: path
          description: IMDb ID de la película
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: Pelicula no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    MoviesResponse:
      type: object
      properties:
        Response:
          type: string
          example: "True"
        Search:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
        totalResults:
          type: string  
        Error:
          type: string
    Movie:
      type: object
      properties:
        Title:
          type: string
          example: "The Shawshank Redemption"
        Year: 
          type: string
          example: "1994"
        imdbID:
          type: string
          example: "tt0111161"
        Type:
          type: string
          example: "movie"
        Poster:
          type: string
          example: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg"
    Error:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de error
        error:
          type: string
          description: Tipo de error