openapi: 3.0.0
info:
  title: API de Direcciones
  version: 1.0.0
  description: API para gestionar reseñas de películas

paths:

  /movieapp/v1/reviews/{movieId}:
    get:
      tags:
        - Reviews
      summary: Obtener reseñas de una película
      parameters:
        - name: movieId
          in: path
          required: true
          description: ID de la película
          schema:
            type: string
      responses:
        '200':
          description: Lista de reseñas obtenida correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  reviews:
                    type: array
                    items:
                      $ref: '#/components/schemas/Review'
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "El parámetro movieId es requerido"
                error: "Bad Request"
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Error inesperado en el servidor"
                error: "Internal Server Error"

  /movieapp/v1/reviews/add-review:
    post:
      tags:
        - Reviews
      summary: Agregar una reseña a una película
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewInput'
      responses:
        '200':
          description: Reseña agregada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Error en la solicitud
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Faltan campos requeridos"
                error: "Bad Request"
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: "Error inesperado en el servidor"
                error: "Internal Server Error"

components:
  schemas:
    Review:
      type: object
      properties:
        _id:
          type: string
          description: ID de la reseña
        userId:
          type: string
          description: ID del usuario que hizo la reseña
        movieId:
          type: string
          description: ID de la película
        rating:
          type: number
          description: Puntuación de la película (1-10)
        review:
          type: string
          description: Texto de la reseña
        createdAt:
          type: string
          format: date-time
          description: Fecha de creación de la reseña
        __v:
          type: number
          description: Versión del documento en la base de datos

    ReviewInput:
      type: object
      required:
        - userId
        - movieId
        - rating
        - review
      properties:
        userId:
          type: string
          description: ID del usuario que hace la reseña
        movieId:
          type: string
          description: ID de la película
        rating:
          type: number
          description: Puntuación de la película (1-10)
        review:
          type: string
          description: Texto de la reseña

    Error:
      type: object
      properties:
        message:
          type: string
          description: Descripción del error
        error:
          type: string
          description: Tipo de error
